// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	GetActiveTgBotUsers(ctx context.Context) ([]int64, error)
	GetLichessMembers(ctx context.Context) ([]string, error)
	InsertMember(ctx context.Context, arg InsertMemberParams) error
	InsertTgBotUsers(ctx context.Context, arg InsertTgBotUsersParams) error
	UpdateTgBotUsers(ctx context.Context, arg UpdateTgBotUsersParams) error
}

var _ Querier = (*Queries)(nil)
